<a href="https://colab.research.google.com/github/geopard26/MDS/blob/main/Linear_Algebra_week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
B=np.array([[-2,1,1],[1,-1,2],[-1,3,-1]])
A=np.array([[-1,2,0],[2,1,2],[3, 2, 1]])
Ab=np.linalg.inv(B).dot(A.dot(B))
print("new transformation matrix in base B")
print(Ab)

LinAlgError: ignored

In [ ]:
from re import X
import numpy as np
def unit_vector(vector):
    """ Returns the unit vector of the vector.  """
    return vector / np.linalg.norm(vector)
def angle_between(v1, v2):
    """ Returns the angle in radians between vectors 'v1' and 'v2'::
            >>> angle_between((1, 0, 0), (0, 1, 0))
            1.5707963267948966
            >>> angle_between((1, 0, 0), (1, 0, 0))
            0.0
            >>> angle_between((1, 0, 0), (-1, 0, 0))
            3.141592653589793
    """
    v1_u = unit_vector(v1)
    v2_u = unit_vector(v2)
    return np.arccos(np.clip(np.dot(v1_u, v2_u), -1.0, 1.0))

x = (3, 1, 2, 5)
y = (-1, 4, -3, 0)
print(np.cos(np.rad2deg(angle_between(x, y))))

0.07365035843105391


In [ ]:
print(22/9 - 5/26)
print(-11/9 - 25/26)

2.252136752136752
-2.183760683760684


In [ ]:
import numpy as np

sin_value = -np.pi/4
angle = np.arcsin(sin_value)

print(angle)

-0.9033391107665127


In [ ]:
sin_alpha = -np.pi/4
cos_beta = np.pi/5

print(np.arccos(cos_beta))


0.8914064000439458


In [ ]:
import numpy as np

x = np.pi/5  # пример значения косинуса
theta_rad = np.arccos(x)  # угол в радианах
theta_deg = np.rad2deg(theta_rad)  # угол в градусах

print(theta_deg)

51.07382455346838


In [ ]:
import numpy as np

sin_alpha = -np.pi/4
cos_beta = np.pi/5

# Находим углы по значениям синуса и косинуса
alpha_rad = np.arcsin(sin_alpha)
beta_rad = np.arccos(cos_beta)

# Преобразовываем углы из радиан в градусы
alpha_deg = np.rad2deg(alpha_rad)
beta_deg = np.rad2deg(beta_rad)

print(alpha_deg, beta_deg)


-51.75751851602197 51.07382455346838


In [ ]:
print(np.sin(45))
print(np.pi/4)

0.8509035245341184
0.7853981633974483


In [ ]:
# Сначала выведите норму вектора a, потом вектора b.
from numpy import array, inf
from numpy.linalg import norm
# Данные:
d = array([20, -4, 8, 2])

print(norm(d, 1))
print(norm(d, 2))

34.0
22.0


In [ ]:
from numpy import array, inf
from numpy.linalg import norm
from math import sqrt
# Данные:
a = array([18])
b = array([7])
c = -3*a + 5*b

c_norm = 9*a**2 - 15*a*b + 25*b**2
print(9*a**2, -15*a*b, 25*b**2)

print(sqrt(c_norm))

[2916] [-1890] [1225]
47.44470465710583


In [ ]:
a = array([2])
b = array([5])
c = 3*a - b

c_norm = 9*a**2 - 3*a*b + b**2
print(9*a**2, -15*a*b, 25*b**2)
print(c_norm)
print(sqrt(c_norm))

[36] [-150] [625]
[31]
5.5677643628300215


In [ ]:
from numpy import array, inf
from numpy.linalg import norm
from math import sqrt
a = array([22, 4, -6, 3.9, 7])
b = array([12, -0.5, 6, 42, 1])
print(norm(a-b,1))
print(norm(a-b))
print(norm(a-b, inf))

70.6
41.85522667481327
38.1


In [ ]:
from numpy import array
from numpy.linalg import norm

a = array([-4, 6, 12])
b = array([2, -8, 3])
c = array([5, 3, -1])

cos_ab = a @ b / norm(a) / norm(b)
cos_ac = a @ c / norm(a) / norm(c)
cos_bc = b @ c / norm(b) / norm(c)
print(cos_ab, cos_ac, cos_bc)

-0.16280082351376848 -0.1690308509457033 -0.32746850462500326


In [ ]:
a = array([-1, 0.5, 3.5, 1])
b = array([6, 10, -4, 8])
c = array([-5, 10, 10, 2.5])
j = -4*a - 2.5*b + 1.2*c

print(j)
print(norm(j, 1))

[-17. -15.   8. -21.]
61.0


In [ ]:
from numpy import inf
f = array([8, -16, -4, 5])

print(norm(f, 1))
print(norm(f))
print(norm(f, inf))

33.0
19.0
16.0


In [ ]:
a = array([0.6, 1.5, 2.4])
b = array([-3.5, 2, -0.5])

print(a @ b)

-0.30000000000000004


In [ ]:
W_example = [4, 3, 3]
V_example = [5, 3, 3]
C_example = 6

def knapsack_dynamic(W, V, C): # O(nC)\n",
    n = len(W)
    tbl = [[0] * (C + 1) for _ in range(n + 1)]
    for i in range(1, n + 1):
      for j in range(C + 1):
        tbl[i][j] = tbl[i - 1][j]
        if j >= W[i - 1]:
          tbl[i][j] = max(
              tbl[i][j],
              tbl[i - 1][j - W[i - 1]] + V[i - 1]
          )
    print("\n".join([str(l) for l in tbl]))
    return tbl[-1][-1]

In [ ]:
W_example = [1, 4, 5,  4,  3,  3, 2, 1]
V_example = [4, 6, 20, 10, 16, 7, 13, 1]
C_example = 12

In [ ]:
knapsack_dynamic(W_example, V_example, C_example)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
[0, 4, 4, 4, 6, 10, 10, 10, 10, 10, 10, 10, 10]
[0, 4, 4, 4, 6, 20, 24, 24, 24, 26, 30, 30, 30]
[0, 4, 4, 4, 10, 20, 24, 24, 24, 30, 34, 34, 34]
[0, 4, 4, 16, 20, 20, 24, 26, 36, 40, 40, 40, 46]
[0, 4, 4, 16, 20, 20, 24, 27, 36, 40, 40, 43, 47]
[0, 4, 13, 17, 20, 29, 33, 33, 37, 40, 49, 53, 53]
[0, 4, 13, 17, 20, 29, 33, 34, 37, 40, 49, 53, 54]


54

In [ ]:
W_example = [3, 8, 8,  2,  1,  8, 2, 3]
V_example = [5, 4, 7,  5,  11, 20, 18, 20]
C_example = 12

In [ ]:
knapsack_dynamic(W_example, V_example, C_example)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
[0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 9, 9]
[0, 0, 0, 5, 5, 5, 5, 5, 7, 7, 7, 12, 12]
[0, 0, 5, 5, 5, 10, 10, 10, 10, 10, 12, 12, 12]
[0, 11, 11, 16, 16, 16, 21, 21, 21, 21, 21, 23, 23]
[0, 11, 11, 16, 16, 16, 21, 21, 21, 31, 31, 36, 36]
[0, 11, 18, 29, 29, 34, 34, 34, 39, 39, 39, 49, 49]
[0, 11, 18, 29, 31, 38, 49, 49, 54, 54, 54, 59, 59]


59

In [ ]:
W_example = [9, 7,  1,   1,   5,  5, 4, 2]
V_example = [2, 17, 19,  19,  6, 17, 15, 2]
C_example = 12

In [ ]:
knapsack_dynamic(W_example, V_example, C_example)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2]
[0, 0, 0, 0, 0, 0, 0, 17, 17, 17, 17, 17, 17]
[0, 19, 19, 19, 19, 19, 19, 19, 36, 36, 36, 36, 36]
[0, 19, 38, 38, 38, 38, 38, 38, 38, 55, 55, 55, 55]
[0, 19, 38, 38, 38, 38, 38, 44, 44, 55, 55, 55, 55]
[0, 19, 38, 38, 38, 38, 38, 55, 55, 55, 55, 55, 61]
[0, 19, 38, 38, 38, 38, 53, 55, 55, 55, 55, 70, 70]
[0, 19, 38, 38, 40, 40, 53, 55, 55, 57, 57, 70, 70]


70

23

32

32

21

1,4;4,6;5,20;4,10;3,16;3,7;2,13;1,1

3,5;8,4;8,7;2,5;1,11;8,20;2,18;3,20

9,2;7,17;1,19;1,19;5,6;5,17;4,15;2,2

O(n)

In [ ]:
from numpy import array
from numpy.linalg import norm

x = array([2, -2, -1])
y = array([-4, 3, 0])

cos_angle = x @ y / norm(x) / norm(y)

print(cos_angle)

-0.9333333333333333


In [ ]:
# программа для рассчета детерминанта матрицы

import numpy as np

def calculate_determinant(matrix):
    # Check if the matrix is square
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError("Matrix must be square to calculate determinant")

    # Calculate determinant
    determinant = np.linalg.det(matrix)

    return determinant

# Example usage
matrix = np.array([[1, 6], [-4, 3]])
determinant = calculate_determinant(matrix)
print(f"Determinant of the matrix:\n{matrix}\n\nis {determinant}")


Determinant of the matrix:
[[ 1  6]
 [-4  3]]

is 27.0


In [ ]:
import numpy as np

# Define the eigenvectors and eigenvalues
P = np.array([[2, 1],
              [1, 4]])

D = np.array([[2, 0],
              [0, -5]])

# Calculate the inverse of P
P_inv = np.linalg.inv(P)

# Verify that P_inv is the inverse of P
identity = np.dot(P, P_inv)

# Calculate the diagonalized form of A
A = np.dot(np.dot(P_inv, D), P)

print("Diagonalized Matrix D:")
print(D)

print("\nInverse of P:")
print(P_inv)

print("\nIdentity Matrix (P * P_inv):")
print(identity)

print("\nDiagonalized Matrix A:")
print(A)


Diagonalized Matrix D:
[[ 2  0]
 [ 0 -5]]

Inverse of P:
[[ 0.57142857 -0.14285714]
 [-0.14285714  0.28571429]]

Identity Matrix (P * P_inv):
[[1. 0.]
 [0. 1.]]

Diagonalized Matrix A:
[[ 3.  4.]
 [-2. -6.]]


In [ ]:
# программа для рассчета детерминанта матрицы на основе функции numpy

from numpy import array
from numpy.linalg import det

A = array([[-6, 12, 0, 0], [12, -18, -6, 0], [6, 12, -6, 12], [-6, 6, 6, 6]])
print(det(A))

-3887.9999999999973


In [ ]:
# программа для вычисления eigenvalues
from numpy import array
import numpy.linalg as LA

A = array([[2, 1],
           [-2, -1]])
w, v = LA.eig(A)
print(w)

[1. 0.]


In [ ]:
import numpy as np

def compute_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

# Пример использования:
A = np.array([[2, 2], [-1, -1]])

eigenvalues, eigenvectors = compute_eigenvectors(A)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)


Собственные значения:
[1. 0.]

Собственные векторы:
[[ 0.89442719 -0.70710678]
 [-0.4472136   0.70710678]]


In [ ]:
import numpy as np

def compute_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

# Пример использования:
A = np.array([[2, -1, 1], [2, 1,-2], [1, 1, -2]])

eigenvalues, eigenvectors = compute_eigenvectors(A)

print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)


Собственные значения:
[ 0.99999999  1.00000001 -1.        ]

Собственные векторы:
[[-4.08248286e-01 -4.08248295e-01 -4.19516918e-17]
 [-8.16496583e-01 -8.16496579e-01  7.07106781e-01]
 [-4.08248291e-01 -4.08248290e-01  7.07106781e-01]]


In [ ]:
import numpy as np

# Создаем матрицу
B = np.array([[1, -3, 1], [-5, 0, 4], [-7, -5, 1]])
T = np.array([[1, 3, 2], [0, 1, -2], [1, 4, -1]])

# Считаем обратную матрицу
T_inv = np.linalg.inv(T)
T_inv_B = np.dot(T_inv, B)

print(np.dot(T_inv_B, T))

[[ -51. -215.   65.]
 [  13.   55.  -18.]
 [   7.   27.   -2.]]


In [ ]:
def heapify(array, n, i):
    largest = i  # Initialize largest as root
    left = 2 * i + 1  # left = 2*i + 1
    right = 2 * i + 2  # right = 2*i + 2

    # See if left child of root exists and is greater than root
    if left < n and array[left] > array[largest]:
        largest = left

    # See if right child of root exists and is greater than largest so far
    if right < n and array[right] > array[largest]:
        largest = right

    # Change root, if needed
    if largest != i:
        array[i], array[largest] = array[largest], array[i]  # swap
        heapify(array, n, largest)  # Heapify the root

def buildMaxHeap(array):
    n = len(array)
    for i in range(n // 2 - 1, -1, -1):
        heapify(array, n, i)

def heapsort(array):
    n = len(array)
    buildMaxHeap(array)

    for i in range(n - 1, 0, -1):
        array[0], array[i] = array[i], array[0]  # Swap the root of the heap with the last element
        heapify(array, i, 0)

    return array

# Test cases
arr = [3, 2, 1, 4]
print(heapsort(arr))  # [1, 2, 3, 4]

arr = [2011, 397, 614, 3888, 7116, 5059, 2664, 7782, 8945, 4920]
print(heapsort(arr))  # [397, 614, 2011, 2664, 3888, 4920, 5059, 7116, 7782, 8945]


[1, 2, 3, 4]
[397, 614, 2011, 2664, 3888, 4920, 5059, 7116, 7782, 8945]


In [ ]:
print(None)

None
